---
- name: Instalar Apache y desplegar p√°gina web
  hosts: servers
  become: yes
  tasks:

    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Crear archivo index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Servidor configurado con Ansible</h1>"

    - name: Iniciar Apache
      service:
        name: apache2
        state: started
        enabled: yes
